const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, 'styles.css'), 'utf8');
const atlasHtmlPath = path.join(__dirname, 'atlas-h5.html');
const atlasCssPath = path.join(__dirname, 'atlas-h5.css');
const atlasJsPath = path.join(__dirname, 'atlas-h5.js');

assert.match(html, /拓融运营管理系统/);
assert.match(html, /class="login-shell"/);
assert.match(html, /class="login-hero"/);
assert.match(html, /Guizhou Tuorong Technology Co\., Ltd\./);
assert.match(html, /class="login-company-en"/);
assert.match(html, /Tuorong Operations Management System/);
assert.match(html, /class="brand-title-en"/);
assert.match(html, /class="login-logo"[^>]*tuorong-mark\.svg/);
assert.match(html, /class="brand-logo"[^>]*tuorong-mark\.svg/);
assert.match(html, /class="toolbar-search search"/);
assert.doesNotMatch(html, /tuorong-logo-wide\.svg/);
assert.doesNotMatch(html, /资产 → 业务 → 执行 → 结算 → 供需\/供应链/);
assert.doesNotMatch(html, /class="nav-brand"/);
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/tuorong-logo-wide.svg')));
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/tuorong-mark.svg')));
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/login-tech-bg.png')));

assert.match(app, /expandedNavGroups/);
assert.match(app, /DEFAULT_EXPANDED_GROUPS/);
assert.match(app, /visibleItems = isExpanded \? group\.items\.filter/);
assert.match(app, /nav-group-toggle/);
assert.match(app, /shouldShowModuleSidebar/);
assert.match(app, /workspace\.classList\.toggle\('no-sidebar'/);
assert.match(app, /permissionsForCurrentModule/);
assert.match(app, /renderDashboard/);
assert.match(app, /loadDashboard/);
assert.match(app, /await showApp\(\)/);
assert.match(app, /dashboardError/);
assert.match(app, /guizhou-business-map/);
assert.match(app, /atl_collection_scenarios/);
assert.match(app, /canCreate/);
assert.match(app, /canDelete/);
assert.match(app, /mod\.readOnly/);
assert.doesNotMatch(app, /PLACEHOLDER_MENU/);
assert.match(css, /\.nav-group\.active/);
assert.match(css, /\.workspace\.no-sidebar/);
assert.match(css, /\.toolbar-search/);
assert.match(css, /\.dashboard-grid/);
assert.match(css, /\.guizhou-map-panel/);
assert.match(css, /\.opportunity-lane/);
assert.match(css, /\.nav-group-toggle \{[^}]*font-size: 15px/);
assert.match(css, /\.nav-item \{[^}]*margin-left: 18px/);
assert.match(css, /\.nav-item \{[^}]*font-size: 13px/);
assert.match(css, /\.login-logo/);
assert.match(css, /\.login-shell/);
assert.match(css, /\.login-hero/);
assert.match(css, /\.login-company-en/);
assert.match(css, /\.brand-title-en/);
assert.match(css, /login-tech-bg\.png/);

assert.ok(fs.existsSync(atlasHtmlPath));
assert.ok(fs.existsSync(atlasCssPath));
assert.ok(fs.existsSync(atlasJsPath));

const atlasHtml = fs.readFileSync(atlasHtmlPath, 'utf8');
const atlasCss = fs.readFileSync(atlasCssPath, 'utf8');
const atlasJs = fs.readFileSync(atlasJsPath, 'utf8');

assert.match(atlasHtml, /Atlas 场景报备/);
assert.match(atlasHtml, /href="\/atlas-h5\.css"/);
assert.match(atlasHtml, /src="\/atlas-h5\.js"/);
assert.doesNotMatch(atlasHtml, /href="\.\/atlas-h5\.css"/);
assert.doesNotMatch(atlasHtml, /src="\.\/atlas-h5\.js"/);
assert.match(atlasHtml, /类目/);
assert.match(atlasHtml, /场景/);
assert.match(atlasHtml, /商家/);
assert.match(atlasHtml, /设备/);
assert.match(atlasHtml, /name="contactName"/);
assert.match(atlasHtml, /name="phone"/);
assert.match(atlasHtml, /name="longitude"/);
assert.match(atlasHtml, /name="latitude"/);
assert.match(atlasHtml, /type="file"/);
assert.match(atlasHtml, /id="scanDeviceBtn"/);
assert.match(atlasHtml, /id="bindingTuplePreview"/);
assert.match(atlasCss, /\.h5-shell/);
assert.match(atlasCss, /\.step-button/);
assert.match(atlasCss, /@media \(max-width: 480px\)/);
assert.match(atlasJs, /\/api\/atlas\/categories/);
assert.match(atlasJs, /\/api\/atlas\/reports/);
assert.match(atlasJs, /navigator\.geolocation/);
assert.match(atlasJs, /bindingTuplePreview/);
assert.match(atlasJs, /scanDeviceBtn/);

console.log('frontend UI tests passed');
