const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, 'styles.css'), 'utf8');
const atlasHtmlPath = path.join(__dirname, 'atlas-h5.html');
const atlasCssPath = path.join(__dirname, 'atlas-h5.css');
const atlasJsPath = path.join(__dirname, 'atlas-h5.js');

assert.match(html, /拓融运营管理系统/);
assert.match(html, /class="[^"]*\blogin-shell\b[^"]*"/);
assert.match(html, /class="[^"]*\blogin-hero\b[^"]*"/);
assert.match(html, /class="[^"]*\blogin-visual\b[^"]*"/);
assert.match(html, /class="[^"]*\blogin-top-tools\b[^"]*"/);
assert.match(html, /class="[^"]*\blogin-panel\b[^"]*"/);
assert.match(html, /class="[^"]*\blogin-submit\b[^"]*"/);
assert.match(html, /class="[^"]*\byudao-login\b[^"]*"/);
assert.match(html, /class="[^"]*\byudao-login__left\b[^"]*"/);
assert.match(html, /class="[^"]*\byudao-login__right\b[^"]*"/);
assert.match(html, /class="[^"]*\byudao-login__form\b[^"]*"/);
assert.match(html, /Guizhou Tuorong Technology Co\., Ltd\./);
assert.match(html, /class="login-company-en"/);
assert.match(html, /Tuorong Operations Management System/);
assert.match(html, /class="brand-title-en"/);
assert.match(html, /class="login-logo"[^>]*tuorong-mark\.svg/);
assert.match(html, /class="brand-logo"[^>]*tuorong-mark\.svg/);
assert.match(html, /class="toolbar-search search"/);
assert.match(html, /id="paginationBar"/);
assert.match(html, /id="pageSizeSelect"/);
assert.match(html, /id="prevPageBtn"/);
assert.match(html, /id="nextPageBtn"/);
assert.match(html, /id="batchDeleteBtn"/);
assert.match(html, /id="accountWatermark"/);
assert.match(html, /class="account-watermark"/);
assert.match(html, /class="[^"]*\byudao-layout\b[^"]*"/);
assert.match(html, /id="sidebarCollapseBtn"/);
assert.match(html, /class="[^"]*\bsidebar-collapse-btn\b[^"]*"/);
assert.match(html, /id="sidebarCollapseBtn"[^>]*>☰<\/button>/);
assert.match(html, /<header class="topbar layout-header">[\s\S]*id="sidebarCollapseBtn"/);
assert.match(html, /class="[^"]*\bsidebar-logo\b[^"]*"/);
assert.match(html, /class="[^"]*\blayout-header\b[^"]*"/);
assert.match(html, /class="[^"]*\bbreadcrumb\b[^"]*"/);
assert.match(html, /class="[^"]*\bheader-tools\b[^"]*"/);
assert.match(html, /class="[^"]*\bquery-panel\b[^"]*"/);
assert.match(html, /class="[^"]*\bcompact-query\b[^"]*"/);
assert.match(html, /class="[^"]*\bquery-controls\b[^"]*"/);
assert.match(html, /class="[^"]*\byudao-side-menu\b[^"]*"/);
assert.doesNotMatch(html, /class="module-sidebar"/);
assert.doesNotMatch(html, /tuorong-logo-wide\.svg/);
assert.doesNotMatch(html, /资产 → 业务 → 执行 → 结算 → 供需\/供应链/);
assert.doesNotMatch(html, /class="nav-brand"/);
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/tuorong-logo-wide.svg')));
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/tuorong-mark.svg')));
assert.ok(fs.existsSync(path.join(root, 'frontend/assets/login-tech-bg.png')));

assert.match(app, /expandedNavGroups/);
assert.match(app, /sidebarCollapsed/);
assert.match(app, /pageSize/);
assert.match(app, /currentPage/);
assert.match(app, /selectedIds/);
assert.match(app, /sortField/);
assert.match(app, /sortDirection/);
assert.match(app, /DEFAULT_EXPANDED_GROUPS/);
assert.match(app, /shouldShowStats/);
assert.match(app, /function shouldShowStats\(\) \{\s*return false;\s*\}/);
assert.match(app, /moduleDesc'\)\.textContent = ''/);
assert.doesNotMatch(app, /支持授权范围内的增删改查/);
assert.match(app, /paginatedRecords/);
assert.match(app, /sortedRecords/);
assert.match(app, /toggleSort/);
assert.match(app, /sortable-header/);
assert.match(app, /sort-indicator/);
assert.match(app, /renderPagination/);
assert.match(app, /toggleSidebar/);
assert.match(app, /sidebarCollapseBtn/);
assert.match(app, /appShell\.classList\.toggle\('sidebar-collapsed'/);
assert.match(app, /visibleItems = isExpanded \? group\.items\.filter/);
assert.match(app, /nav-group-toggle/);
assert.match(app, /nav-group-icon/);
assert.doesNotMatch(app, /nav-item-dot/);
assert.match(app, /shouldShowModuleSidebar/);
assert.match(app, /workspace\.classList\.add\('no-sidebar'/);
assert.match(app, /permissionsForCurrentModule/);
assert.match(app, /renderRowActions/);
assert.match(app, /toggleRecordSelection/);
assert.match(app, /toggleSelectAll/);
assert.match(app, /batchDeleteSelected/);
assert.match(app, /selectAllRows/);
assert.match(app, /row-select/);
assert.match(app, /batchDeleteBtn/);
assert.match(app, /table-actions/);
assert.match(app, /openEditor/);
assert.match(app, /closeEditor/);
assert.match(app, /renderDashboard/);
assert.match(app, /loadDashboard/);
assert.match(app, /await showApp\(\)/);
assert.match(app, /dashboardError/);
assert.match(app, /guizhou-business-map/);
assert.match(app, /atl_collection_scenarios/);
assert.match(app, /atlas_workbench/);
assert.match(app, /ATLAS_WORKBENCH_MODULE/);
assert.match(app, /loadAtlasWorkbench/);
assert.match(app, /renderAtlasWorkbench/);
assert.match(app, /renderAtlasWorkbenchTabs/);
assert.match(app, /selectAtlasScene/);
assert.match(app, /\/api\/atlas\/workbench\/summary/);
assert.match(app, /\/api\/atlas\/workbench\/scenes/);
assert.match(app, /\/api\/atlas\/workbench\/records/);
assert.match(app, /\/api\/atlas\/workbench\/categories/);
assert.match(app, /\/api\/atlas\/workbench\/output/);
assert.match(app, /\/api\/atlas\/workbench\/generate/);
assert.match(app, /atlasGenerateSelected/);
assert.match(app, /atlasClearEdits/);
assert.match(app, /canCreate/);
assert.match(app, /canDelete/);
assert.match(app, /mod\.readOnly/);
assert.match(app, /currentUser/);
assert.match(app, /setAccountWatermark/);
assert.match(app, /clearAccountWatermark/);
assert.match(app, /watermarkTextForUser/);
assert.match(app, /encodeURIComponent\(svg\)/);
assert.doesNotMatch(app, /PLACEHOLDER_MENU/);
assert.match(css, /\.nav-group\.active/);
assert.match(css, /\.workspace\.no-sidebar/);
assert.match(css, /\.toolbar-search/);
assert.match(css, /\.dashboard-grid/);
assert.match(css, /\.guizhou-map-panel/);
assert.match(css, /\.opportunity-lane/);
assert.match(css, /\.atlas-workbench/);
assert.match(css, /\.atlas-tabs/);
assert.match(css, /\.atlas-scene-grid/);
assert.match(css, /\.atlas-detail-panel/);
assert.match(css, /\.atlas-record-table/);
assert.match(css, /\.nav-group-toggle \{[^}]*font-size: 14px/);
assert.match(css, /\.nav-item \{[^}]*margin-left: 0/);
assert.match(css, /\.nav-item \{[^}]*font-size: 14px/);
assert.match(css, /\.login-logo/);
assert.match(css, /\.login-shell/);
assert.match(css, /\.login-hero/);
assert.match(css, /\.login-visual/);
assert.match(css, /\.login-top-tools/);
assert.match(css, /\.login-panel/);
assert.match(css, /\.login-submit/);
assert.match(css, /\.yudao-login/);
assert.match(css, /\.yudao-login \.yudao-login__wrap/);
assert.match(css, /\.yudao-login \.yudao-login__form/);
assert.match(css, /\.login-company-en/);
assert.match(css, /\.brand-title-en/);
assert.match(css, /login-tech-bg\.png/);
assert.match(css, /\.account-watermark/);
assert.match(css, /pointer-events: none/);
assert.match(css, /\.yudao-layout/);
assert.match(css, /\.sidebar-collapse-btn/);
assert.match(css, /\.sidebar-collapsed/);
assert.match(css, /\.pagination-bar/);
assert.match(css, /\.page-size-select/);
assert.match(css, /\.selection-col/);
assert.match(css, /\.batch-delete/);
assert.match(css, /\.sortable-header/);
assert.match(css, /\.sort-indicator/);
assert.match(css, /\.modal-panel/);
assert.match(css, /\.modal-panel \{[\s\S]*top: 50%/);
assert.match(css, /\.modal-panel \{[\s\S]*transform: translate\(-50%, -50%\)/);
assert.match(css, /\.layout-header \{[\s\S]*position: sticky/);
assert.match(css, /table td \{[\s\S]*font-size: 12px/);
assert.match(css, /table td \{[\s\S]*height: 40px/);
assert.match(css, /\.sidebar-collapse-btn \{[\s\S]*position: static/);
assert.match(css, /\.pagination-bar \{[\s\S]*margin-top: 8px/);
assert.match(css, /\.pagination-bar label \{[\s\S]*display: inline-flex/);
assert.match(css, /\.pagination-bar label \{[\s\S]*align-items: center/);
assert.match(css, /\.query-panel \.btn \{[\s\S]*font-size: 12px/);
assert.match(css, /\.query-panel \.btn \{[\s\S]*height: 30px/);
assert.match(css, /\.query-panel \.toolbar-search \{[\s\S]*height: 34px/);
assert.match(css, /\.query-panel \.toolbar-search span \{[\s\S]*font-size: 14px/);
assert.match(css, /\.query-panel \.toolbar-search input \{[\s\S]*font-size: 13px/);
assert.match(css, /\.header-tools \.btn \{[\s\S]*font-size: 12px/);
assert.match(css, /--sidebar-bg: #304156/);
assert.match(css, /--layout-bg: #f0f2f5/);
assert.doesNotMatch(css, /Gaode-style console refinement/);
assert.doesNotMatch(css, /\.gaode-console-header/);
assert.doesNotMatch(css, /\.gaode-console-shell/);
assert.match(css, /\.layout-header/);
assert.match(css, /\.breadcrumb/);
assert.match(css, /\.query-panel/);
assert.match(css, /\.compact-query/);
assert.match(css, /\.compact-query \.query-title \{[\s\S]*display: none/);
assert.match(css, /\.compact-query \.query-title \.subtle \{[\s\S]*display: none/);
assert.match(css, /\.compact-query \.query-controls \{[\s\S]*display: flex/);
assert.match(css, /\.compact-query \.toolbar-search \{[\s\S]*max-width: 420px/);
assert.match(css, /\.compact-query \.filters \{[\s\S]*justify-content: flex-start/);
assert.match(css, /\.compact-query \.actions \{[\s\S]*margin-left: auto/);
assert.match(css, /\.compact-query \.actions \{[\s\S]*justify-content: flex-end/);
assert.match(css, /\.query-controls/);
assert.match(css, /\.content-card/);
assert.match(css, /\.drawer-panel/);
assert.match(css, /\.editor-backdrop/);
assert.match(css, /\.table-actions/);
assert.match(css, /--sidebar-bg: #304156/);
assert.match(css, /\.nav-group-icon/);
assert.match(css, /\.nav-group-icon/);

assert.ok(fs.existsSync(atlasHtmlPath));
assert.ok(fs.existsSync(atlasCssPath));
assert.ok(fs.existsSync(atlasJsPath));

const atlasHtml = fs.readFileSync(atlasHtmlPath, 'utf8');
const atlasCss = fs.readFileSync(atlasCssPath, 'utf8');
const atlasJs = fs.readFileSync(atlasJsPath, 'utf8');

assert.match(atlasHtml, /Atlas 场景报备/);
assert.match(atlasHtml, /href="\/atlas-h5\.css"/);
assert.match(atlasHtml, /src="\/atlas-h5\.js"/);
assert.doesNotMatch(atlasHtml, /href="\.\/atlas-h5\.css"/);
assert.doesNotMatch(atlasHtml, /src="\.\/atlas-h5\.js"/);
assert.match(atlasHtml, /类目/);
assert.match(atlasHtml, /场景/);
assert.match(atlasHtml, /商家/);
assert.match(atlasHtml, /设备/);
assert.match(atlasHtml, /name="contactName"/);
assert.match(atlasHtml, /name="phone"/);
assert.match(atlasHtml, /name="longitude"/);
assert.match(atlasHtml, /name="latitude"/);
assert.match(atlasHtml, /type="file"/);
assert.match(atlasHtml, /id="scanDeviceBtn"/);
assert.match(atlasHtml, /id="bindingTuplePreview"/);
assert.match(atlasCss, /\.h5-shell/);
assert.match(atlasCss, /\.step-button/);
assert.match(atlasCss, /@media \(max-width: 480px\)/);
assert.match(atlasJs, /\/api\/atlas\/categories/);
assert.match(atlasJs, /\/api\/atlas\/reports/);
assert.match(atlasJs, /loadReportStats\(\)\.catch/);
assert.match(atlasJs, /navigator\.geolocation/);
assert.match(atlasJs, /bindingTuplePreview/);
assert.match(atlasJs, /scanDeviceBtn/);

console.log('frontend UI tests passed');
