const businessTypes = [
  ['data_collection', '数据采集'],
  ['electricity', '售电业务'],
  ['supply_chain', '供应链业务'],
  ['matching', '供需撮合'],
  ['other', '其他'],
];

function field(name, label, type = 'text', options = {}) {
  return { name, label, type, ...options };
}

const modules = {
  assets: {
    title: '资产中心',
    table: 'assets',
    primaryField: 'name',
    filters: [['all', '全部'], ['valuable', '有效资产'], ['verify', '待核实'], ['key', '重点资产'], ['dormant', '沉睡资产'], ['invalid', '无效资产']],
    fields: [
      field('name', '资产名称', 'text', { required: true }),
      field('assetType', '资产类型', 'select', { options: [['store', '门店'], ['company', '公司'], ['person', '个人']] }),
      field('contactName', '联系人'),
      field('phone', '联系电话'),
      field('wechat', '微信号'),
      field('address', '地址'),
      field('longitude', '经度', 'number'),
      field('latitude', '纬度', 'number'),
      field('businessTags', '可做业务标签'),
      field('assetStatus', '资产状态', 'select', { options: [['valuable', '有效资产'], ['verify', '待核实'], ['key', '重点资产'], ['dormant', '沉睡资产'], ['invalid', '无效资产']] }),
      field('cooperationStage', '合作阶段', 'select', { options: [['untouched', '未接触'], ['contacted', '已接触'], ['interested', '意向中'], ['trial', '试合作'], ['active', '合作中'], ['paused', '暂停合作'], ['failed', '合作失败']] }),
      field('settlementStatus', '结算状态', 'select', { options: [['unsettled', '未结算'], ['settled', '已结算'], ['pending', '待确认']] }),
      field('notes', '备注', 'textarea'),
    ],
  },
  people: {
    title: '人员中心',
    table: 'people',
    primaryField: 'name',
    filters: [['all', '全部'], ['business', '业务人员'], ['collector', '采集人员'], ['owner', '负责人']],
    fields: [
      field('name', '姓名', 'text', { required: true }),
      field('phone', '电话'),
      field('role', '角色', 'select', { options: [['business', '业务人员'], ['collector', '采集人员'], ['owner', '负责人'], ['other', '其他']] }),
      field('area', '区域'),
      field('relatedAsset', '所属门店/资产'),
      field('status', '状态', 'select', { options: [['active', '在用'], ['inactive', '停用']] }),
      field('notes', '备注', 'textarea'),
    ],
  },
  projects: {
    title: '项目/产品中心',
    table: 'projects',
    primaryField: 'projectName',
    filters: [['all', '全部'], ...businessTypes],
    fields: [
      field('projectCode', '项目编号', 'text', { required: true }),
      field('projectName', '项目名称', 'text', { required: true }),
      field('businessType', '业务类型', 'select', { options: businessTypes }),
      field('upstream', '上游甲方'),
      field('pricingRule', '价格/结算规则', 'textarea'),
      field('minPrice', '最低协议单价', 'number'),
      field('maxPrice', '最高协议单价', 'number'),
      field('status', '状态', 'select', { options: [['active', '启用'], ['pending', '待确认'], ['inactive', '停用']] }),
    ],
  },
  opportunities: {
    title: '业务机会管理',
    table: 'opportunities',
    primaryField: 'businessName',
    filters: [['all', '全部'], ['lead', '线索'], ['contacted', '已联系'], ['negotiating', '洽谈中'], ['won', '已成交'], ['lost', '已流失']],
    fields: [
      field('businessName', '业务名称', 'text', { required: true }),
      field('assetName', '客户/门店'),
      field('businessType', '业务类型', 'select', { options: businessTypes }),
      field('owner', '负责人'),
      field('stage', '业务阶段', 'select', { options: [['lead', '线索'], ['contacted', '已联系'], ['negotiating', '洽谈中'], ['won', '已成交'], ['lost', '已流失']] }),
      field('expectedAmount', '预计金额', 'number'),
      field('dealAmount', '成交金额', 'number'),
      field('nextFollowDate', '下次跟进日期', 'date'),
      field('notes', '备注', 'textarea'),
    ],
  },
  execution_tasks: {
    title: '执行任务管理',
    table: 'execution_tasks',
    primaryField: 'taskName',
    filters: [['all', '全部'], ['data_collection', '数据采集'], ['electricity', '售电'], ['supply_chain', '供应链'], ['matching', '供需']],
    fields: [
      field('taskName', '任务名称', 'text', { required: true }),
      field('businessType', '业务类型', 'select', { options: businessTypes }),
      field('assetName', '关联门店/客户'),
      field('projectName', '关联项目'),
      field('executor', '执行人'),
      field('taskDate', '执行日期', 'date'),
      field('reportedHours', '日报工时', 'number'),
      field('approvedHours', '审批通过工时', 'number'),
      field('status', '执行状态', 'select', { options: [['pending', '待执行'], ['doing', '执行中'], ['done', '已完成'], ['blocked', '受阻']] }),
      field('result', '执行结果', 'textarea'),
    ],
  },
  equipment_records: {
    title: '设备出入库',
    table: 'equipment_records',
    primaryField: 'recordTitle',
    filters: [['all', '全部'], ['inbound', '入库'], ['outbound', '出库'], ['return', '归还'], ['damage', '报损'], ['spare', '备用']],
    fields: [
      field('recordTitle', '记录名称', 'text', { required: true }),
      field('equipmentType', '设备类型', 'select', { options: [['power_bank', '充电宝'], ['memory_card', '内存卡'], ['camera_cable', '摄像头线'], ['waist_bag', '腰包'], ['other', '其他']] }),
      field('flowType', '出入库类型', 'select', { options: [['inbound', '入库'], ['outbound', '出库'], ['return', '归还'], ['damage', '报损'], ['spare', '备用']] }),
      field('quantity', '数量', 'number'),
      field('assetName', '关联门店/任务'),
      field('handler', '经办人'),
      field('recordDate', '日期', 'date'),
      field('status', '状态', 'select', { options: [['normal', '正常'], ['pending', '待确认'], ['lost', '遗失'], ['damaged', '损坏']] }),
      field('notes', '备注', 'textarea'),
    ],
  },
  settlements: {
    title: '结算管理',
    table: 'settlements',
    primaryField: 'settlementName',
    filters: [['all', '全部'], ['receivable', '应收'], ['payable', '应付'], ['paid', '已结']],
    fields: [
      field('settlementName', '结算名称', 'text', { required: true }),
      field('businessType', '业务类型', 'select', { options: businessTypes }),
      field('relatedObject', '关联对象'),
      field('direction', '收付方向', 'select', { options: [['receivable', '上游应收'], ['payable', '下游应付']] }),
      field('amount', '金额', 'number'),
      field('cost', '成本', 'number'),
      field('profit', '毛利润', 'number'),
      field('status', '结算状态', 'select', { options: [['pending', '待结算'], ['paid', '已结算'], ['partial', '部分结算']] }),
      field('invoiceStatus', '发票状态'),
      field('notes', '备注', 'textarea'),
    ],
  },
  supply_demand: {
    title: '供需管理',
    table: 'supply_demand',
    primaryField: 'demandTitle',
    filters: [['all', '全部'], ['demand', '需求'], ['supply', '供应'], ['matched', '已撮合']],
    fields: [
      field('demandTitle', '需求/供应标题', 'text', { required: true }),
      field('recordType', '类型', 'select', { options: [['demand', '需求'], ['supply', '供应']] }),
      field('assetName', '关联门店/客户'),
      field('category', '品类/服务'),
      field('quantity', '数量'),
      field('budget', '预算/报价', 'number'),
      field('matchStatus', '撮合状态', 'select', { options: [['pending', '待撮合'], ['matched', '已撮合'], ['failed', '未成交']] }),
      field('notes', '备注', 'textarea'),
    ],
  },
  supply_chain: {
    title: '供应链管理',
    table: 'supply_chain_orders',
    primaryField: 'orderName',
    filters: [['all', '全部'], ['pending', '待处理'], ['shipping', '配送中'], ['done', '已完成']],
    fields: [
      field('orderName', '订单名称', 'text', { required: true }),
      field('supplier', '供应商'),
      field('assetName', '采购门店/客户'),
      field('productName', '商品/服务'),
      field('quantity', '数量', 'number'),
      field('unitPrice', '单价', 'number'),
      field('totalAmount', '总金额', 'number'),
      field('deliveryStatus', '配送状态', 'select', { options: [['pending', '待处理'], ['shipping', '配送中'], ['done', '已完成']] }),
      field('paymentStatus', '回款状态'),
      field('notes', '备注', 'textarea'),
    ],
  },
  issues: {
    title: '问题管理',
    table: 'issues',
    primaryField: 'title',
    filters: [['all', '全部'], ['open', '未处理'], ['doing', '处理中'], ['resolved', '已解决']],
    fields: [
      field('title', '问题标题', 'text', { required: true }),
      field('sourceModule', '来源模块'),
      field('relatedObject', '关联对象'),
      field('owner', '负责人'),
      field('priority', '优先级', 'select', { options: [['high', '高'], ['medium', '中'], ['low', '低']] }),
      field('status', '处理状态', 'select', { options: [['open', '未处理'], ['doing', '处理中'], ['resolved', '已解决']] }),
      field('dueDate', '截止日期', 'date'),
      field('description', '问题描述', 'textarea'),
      field('result', '处理结果', 'textarea'),
    ],
  },
};

function getModule(key) {
  return modules[key];
}

module.exports = { businessTypes, modules, getModule };
